# Загрузка городов в БД
список городов с базовой инфой (geonames) и индексы numbeo

In [1]:
from datetime import date
from os import getenv

import pandas as pd
from sqlalchemy import create_engine, text

In [3]:
engine = create_engine(getenv("SQLALCHEMY_RELOHELPER_URL"))

### Подготовка df

In [13]:
df = pd.read_pickle("./data/geonameid.pkl")

In [14]:
df.head(3)

,city,state_code,state_name,country_code,country,city_country,cost_of_living,rent,cost_of_living_plus_rent,groceries,...,pollution,link,country_code2,geonameid,population,latitude,longitude,timezone,match_count,match_source
city_id,,,,,,,,,,,,,,,,,,,,,
3,Zurich,NaN,NaN,CHE,Switzerland,"Zurich, Switzerland",123.9,71.3,99.6,125.6,...,25.3,https://www.numbeo.com/cost-of-living/in/Zuric...,CH,2657896.0,415367.0,47.36667,8.55000,Europe/Zurich,1,alt_exact:Zurich
8,Geneva,NaN,NaN,CHE,Switzerland,"Geneva, Switzerland",118.4,64.3,93.4,116.0,...,24.2,https://www.numbeo.com/cost-of-living/in/Genev...,CH,2660646.0,201741.0,46.20222,6.14569,Europe/Zurich,1,alt_exact:Geneva
2,Basel,NaN,NaN,CHE,Switzerland,"Basel, Switzerland",114.0,47.3,83.2,113.7,...,31.4,https://www.numbeo.com/cost-of-living/in/Basel...,CH,2661604.0,177595.0,47.55839,7.57327,Europe/Zurich,1,name_exact:Basel

In [15]:
df.loc[2, "link"]

'https://www.numbeo.com/cost-of-living/in/Basel?displayCurrency=USD'

In [16]:
df.columns

Index(['city', 'state_code', 'state_name', 'country_code', 'country',
       'city_country', 'cost_of_living', 'rent', 'cost_of_living_plus_rent',
       'groceries', 'local_purchasing_power', 'quality_of_life',
       'property_price_to_income_ratio', 'traffic_commute_time', 'climate',
       'safety', 'health_care', 'pollution', 'link', 'country_code2',
       'geonameid', 'population', 'latitude', 'longitude', 'timezone',
       'match_count', 'match_source'],
      dtype='str')

# I form a table of indices numbeo by city + upload it to the database

In [ ]:
# df_city_index = df.iloc[:, [0] + list(range(5, 17))].copy()
# # добавляю столбцы когда и кем добавлены данные в таблицу
# df_city_index.loc[:, ("sys_updated_date", "sys_updated_by")] = (
#     date.today(),
#     getenv("NB_USER"),
# )
# df_city_index.head(2)

In [ ]:
# df_city_index.to_sql("numbeo_index_by_city", engine, index=False)
# stmt4 = "ALTER TABLE numbeo_index_by_city ADD CONSTRAINT PK_numbeo_index_by_city PRIMARY KEY (city_id)"
# stmt5 = "ALTER TABLE numbeo_index_by_city ADD CONSTRAINT FK_numbeo_index_by_city FOREIGN KEY (city_id) REFERENCES public.city (city_id)"
# with engine.connect() as connection:
#     connection.execute(text(stmt4))
#     connection.execute(text(stmt5))
#     connection.commit()

Приведение `geonameid` и `population` к типу `Int64`

In [24]:
df["geonameid"] = df["geonameid"].astype("Int64")
df["population"] = df["population"].astype("Int64")

In [25]:
df

,city,state_code,state_name,country_code,country,city_country,cost_of_living,rent,cost_of_living_plus_rent,groceries,...,pollution,link,country_code2,geonameid,population,latitude,longitude,timezone,match_count,match_source
city_id,,,,,,,,,,,,,,,,,,,,,
3,Zurich,NaN,NaN,CHE,Switzerland,"Zurich, Switzerland",123.9,71.3,99.6,125.6,...,25.3,https://www.numbeo.com/cost-of-living/in/Zuric...,CH,2657896,415367,47.36667,8.55000,Europe/Zurich,1,alt_exact:Zurich
8,Geneva,NaN,NaN,CHE,Switzerland,"Geneva, Switzerland",118.4,64.3,93.4,116.0,...,24.2,https://www.numbeo.com/cost-of-living/in/Genev...,CH,2660646,201741,46.20222,6.14569,Europe/Zurich,1,alt_exact:Geneva
2,Basel,NaN,NaN,CHE,Switzerland,"Basel, Switzerland",114.0,47.3,83.2,113.7,...,31.4,https://www.numbeo.com/cost-of-living/in/Basel...,CH,2661604,177595,47.55839,7.57327,Europe/Zurich,1,name_exact:Basel
535,Lugano,NaN,NaN,CHE,Switzerland,"Lugano, Switzerland",113.8,44.2,81.6,109.9,...,NaN,https://www.numbeo.com/cost-of-living/in/Lugan...,CH,2659836,63185,46.01008,8.96004,Europe/Zurich,1,name_exact:Lugano
5,Lausanne,NaN,NaN,CHE,Switzerland,"Lausanne, Switzerland",113.0,52.8,85.2,111.4,...,NaN,https://www.numbeo.com/cost-of-living/in/Lausa...,CH,2659994,139111,46.51600,6.63282,Europe/Zurich,1,name_exact:Lausanne
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,Indore,NaN,NaN,IND,India,"Indore, India",18.1,4.0,11.6,20.5,...,60.2,https://www.numbeo.com/cost-of-living/in/Indor...,IN,1269743,1994397,22.71792,75.83330,Asia/Kolkata,1,name_exact:Indore
621,Guwahati,NaN,NaN,IND,India,"Guwahati, India",17.7,3.3,11.0,21.3,...,75.8,https://www.numbeo.com/cost-of-living/in/Guwah...,IN,1271476,962334,26.18440,91.74580,Asia/Kolkata,1,name_exact:Guwahati
622,Lucknow,NaN,NaN,IND,India,"Lucknow (Lakhnau), India",17.5,3.4,11.0,19.8,...,77.9,https://www.numbeo.com/cost-of-living/in/Luckn...,IN,1264733,2472011,26.83928,80.92313,Asia/Kolkata,1,name_exact:Lucknow
623,Rajkot,NaN,NaN,IND,India,"Rajkot, India",17.1,3.2,10.6,19.9,...,59.8,https://www.numbeo.com/cost-of-living/in/Rajko...,IN,1258847,1390640,22.29161,70.79322,Asia/Kolkata,1,alt_exact:Rajkot
624,Coimbatore,NaN,NaN,IND,India,"Coimbatore, India",16.9,3.4,10.6,20.8,...,63.4,https://www.numbeo.com/cost-of-living/in/Coimb...,IN,1273865,2136916,11.00555,76.96612,Asia/Kolkata,1,name_exact:Coimbatore

Из главного большого датафрейма формирую 3 таблицы для их последующей отправки в БД

In [37]:
audit_date = date.today()
audit_by = getenv("NB_USER")

df_numbeo_city_indices = df.loc[
    :,
    [
        "geonameid",
        "cost_of_living",
        "rent",
        "cost_of_living_plus_rent",
        "groceries",
        "local_purchasing_power",
        "quality_of_life",
        "property_price_to_income_ratio",
        "traffic_commute_time",
        "climate",
        "safety",
        "health_care",
        "pollution",
    ],
].copy()

df_cities = df.loc[
    :,
    [
        "geonameid",
        "city",
        "state_code",
        "country_code",
        "population",
        "latitude",
        "longitude",
        "timezone",
    ],
].copy()

df_numbeo_city_links = df.loc[
    :,
    [
        "geonameid",
        "link",
    ],
].copy()

for d in (df_numbeo_city_indices, df_cities, df_numbeo_city_links):
    d.loc[:, "updated_date"] = audit_date
    d.loc[:, "updated_by"] = audit_by

In [30]:
df_numbeo_city_indices.head(3)

,geonameid,cost_of_living,rent,cost_of_living_plus_rent,groceries,local_purchasing_power,quality_of_life,property_price_to_income_ratio,traffic_commute_time,climate,safety,health_care,pollution,updated_date,updated_by
city_id,,,,,,,,,,,,,,,
3,2657896,123.9,71.3,99.6,125.6,176.4,204.6,11.9,36.9,81.5,76.7,70.1,25.3,2026-03-12,analyst_k2
8,2660646,118.4,64.3,93.4,116.0,161.3,200.5,13.0,32.6,82.6,70.5,69.9,24.2,2026-03-12,analyst_k2
2,2661604,114.0,47.3,83.2,113.7,186.9,206.3,9.8,36.9,82.8,68.9,69.3,31.4,2026-03-12,analyst_k2

In [31]:
df_cities.head(3)

,geonameid,city,state_code,country_code,population,latitude,longitude,timezone,updated_date,updated_by
city_id,,,,,,,,,,
3,2657896,Zurich,NaN,CHE,415367,47.36667,8.55000,Europe/Zurich,2026-03-12,analyst_k2
8,2660646,Geneva,NaN,CHE,201741,46.20222,6.14569,Europe/Zurich,2026-03-12,analyst_k2
2,2661604,Basel,NaN,CHE,177595,47.55839,7.57327,Europe/Zurich,2026-03-12,analyst_k2

In [38]:
df_numbeo_city_links = df_numbeo_city_links.rename(columns={"link": "numbeo_link"})
df_numbeo_city_links.insert(2, "climate_link", None)
df_numbeo_city_links.head(3)

,geonameid,numbeo_link,climate_link,updated_date,updated_by
city_id,,,,,
3,2657896,https://www.numbeo.com/cost-of-living/in/Zuric...,None,2026-03-12,analyst_k2
8,2660646,https://www.numbeo.com/cost-of-living/in/Genev...,None,2026-03-12,analyst_k2
2,2661604,https://www.numbeo.com/cost-of-living/in/Basel...,None,2026-03-12,analyst_k2

In [41]:

df_numbeo_city_indices.to_sql(
    "numbeo_city_indices", engine, if_exists="append", index=True
)

df_cities.to_sql("cities", engine, if_exists="append", index=True)

df_numbeo_city_links.to_sql("city_source_links", engine, if_exists="append", index=True)

527

In [4]:
stmt = """
ALTER TABLE public.cities
ADD CONSTRAINT cities_pkey PRIMARY KEY (city_id)
"""

with engine.connect() as connection:
    connection.execute(text(stmt))
    connection.commit()

In [5]:
stmt1 = """
ALTER TABLE public.cities
ADD CONSTRAINT FK_cities_state
FOREIGN KEY (state_code)
REFERENCES public.state (state_code)
"""

stmt2 = """
ALTER TABLE public.cities
ADD CONSTRAINT FK_cities_country
FOREIGN KEY (country_code)
REFERENCES public.countries (country_code)
"""

with engine.connect() as connection:
    connection.execute(text(stmt1))
    connection.execute(text(stmt2))
    connection.commit()