## Тесты, эксперименты

In [1]:
from os import getenv
from datetime import date

import pandas as pd
from sqlalchemy import create_engine, text

In [2]:
engine = create_engine(getenv("SQLALCHEMY_RELOHELPER_URL"))

In [2]:
df = pd.read_pickle("./data/geonameid.pkl")
len(df)

527

In [6]:
df

,city,state_code,state_name,country_code,country,city_country,cost_of_living,rent,cost_of_living_plus_rent,groceries,...,pollution,link,country_code2,geonameid,population,latitude,longitude,timezone,match_count,match_source
city_id,,,,,,,,,,,,,,,,,,,,,
3,Zurich,NaN,NaN,CHE,Switzerland,"Zurich, Switzerland",123.9,71.3,99.6,125.6,...,25.3,https://www.numbeo.com/cost-of-living/in/Zuric...,CH,2657896.0,415367.0,47.36667,8.55000,Europe/Zurich,1,alt_exact:Zurich
8,Geneva,NaN,NaN,CHE,Switzerland,"Geneva, Switzerland",118.4,64.3,93.4,116.0,...,24.2,https://www.numbeo.com/cost-of-living/in/Genev...,CH,2660646.0,201741.0,46.20222,6.14569,Europe/Zurich,1,alt_exact:Geneva
2,Basel,NaN,NaN,CHE,Switzerland,"Basel, Switzerland",114.0,47.3,83.2,113.7,...,31.4,https://www.numbeo.com/cost-of-living/in/Basel...,CH,2661604.0,177595.0,47.55839,7.57327,Europe/Zurich,1,name_exact:Basel
535,Lugano,NaN,NaN,CHE,Switzerland,"Lugano, Switzerland",113.8,44.2,81.6,109.9,...,NaN,https://www.numbeo.com/cost-of-living/in/Lugan...,CH,2659836.0,63185.0,46.01008,8.96004,Europe/Zurich,1,name_exact:Lugano
5,Lausanne,NaN,NaN,CHE,Switzerland,"Lausanne, Switzerland",113.0,52.8,85.2,111.4,...,NaN,https://www.numbeo.com/cost-of-living/in/Lausa...,CH,2659994.0,139111.0,46.51600,6.63282,Europe/Zurich,1,name_exact:Lausanne
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,Indore,NaN,NaN,IND,India,"Indore, India",18.1,4.0,11.6,20.5,...,60.2,https://www.numbeo.com/cost-of-living/in/Indor...,IN,1269743.0,1994397.0,22.71792,75.83330,Asia/Kolkata,1,name_exact:Indore
621,Guwahati,NaN,NaN,IND,India,"Guwahati, India",17.7,3.3,11.0,21.3,...,75.8,https://www.numbeo.com/cost-of-living/in/Guwah...,IN,1271476.0,962334.0,26.18440,91.74580,Asia/Kolkata,1,name_exact:Guwahati
622,Lucknow,NaN,NaN,IND,India,"Lucknow (Lakhnau), India",17.5,3.4,11.0,19.8,...,77.9,https://www.numbeo.com/cost-of-living/in/Luckn...,IN,1264733.0,2472011.0,26.83928,80.92313,Asia/Kolkata,1,name_exact:Lucknow
623,Rajkot,NaN,NaN,IND,India,"Rajkot, India",17.1,3.2,10.6,19.9,...,59.8,https://www.numbeo.com/cost-of-living/in/Rajko...,IN,1258847.0,1390640.0,22.29161,70.79322,Asia/Kolkata,1,alt_exact:Rajkot
624,Coimbatore,NaN,NaN,IND,India,"Coimbatore, India",16.9,3.4,10.6,20.8,...,63.4,https://www.numbeo.com/cost-of-living/in/Coimb...,IN,1273865.0,2136916.0,11.00555,76.96612,Asia/Kolkata,1,name_exact:Coimbatore

In [8]:
df.loc[:, "link"].to_dict()

{3: 'https://www.numbeo.com/cost-of-living/in/Zurich?displayCurrency=USD',
 8: 'https://www.numbeo.com/cost-of-living/in/Geneva?displayCurrency=USD',
 2: 'https://www.numbeo.com/cost-of-living/in/Basel?displayCurrency=USD',
 535: 'https://www.numbeo.com/cost-of-living/in/Lugano?displayCurrency=USD',
 5: 'https://www.numbeo.com/cost-of-living/in/Lausanne?displayCurrency=USD',
 7: 'https://www.numbeo.com/cost-of-living/in/George-Town-Cayman-Islands?displayCurrency=USD',
 9: 'https://www.numbeo.com/cost-of-living/in/Bern?displayCurrency=USD',
 13: 'https://www.numbeo.com/cost-of-living/in/Honolulu?displayCurrency=USD',
 11: 'https://www.numbeo.com/cost-of-living/in/New-York?displayCurrency=USD',
 16: 'https://www.numbeo.com/cost-of-living/in/Reykjavik?displayCurrency=USD',
 14: 'https://www.numbeo.com/cost-of-living/in/San-Francisco?displayCurrency=USD',
 76: 'https://www.numbeo.com/cost-of-living/in/Tel-Aviv-Yafo?displayCurrency=USD',
 22: 'https://www.numbeo.com/cost-of-living/in/Oslo?displayCurrency=USD',
 17: 'https://www.numbeo.com/cost-of-living/in/Trondheim?displayCurrency=USD',
 18: 'https://www.numbeo.com/cost-of-living/in/Bergen?displayCurrency=USD',
 15: 'https://www.numbeo.com/cost-of-living/in/Seattle?displayCurrency=USD',
 33: 'https://www.numbeo.com/cost-of-living/in/London?displayCurrency=USD',
 24: 'https://www.numbeo.com/cost-of-living/in/San-Jose?displayCurrency=USD',
 26: 'https://www.numbeo.com/cost-of-living/in/Singapore?displayCurrency=USD',
 23: 'https://www.numbeo.com/cost-of-living/in/Stavanger?displayCurrency=USD',
 28: 'https://www.numbeo.com/cost-of-living/in/Washington?displayCurrency=USD',
 81: 'https://www.numbeo.com/cost-of-living/in/Ramat-Gan?displayCurrency=USD',
 536: 'https://www.numbeo.com/cost-of-living/in/Charleston?displayCurrency=USD',
 152: 'https://www.numbeo.com/cost-of-living/in/Jerusalem?displayCurrency=USD',
 19: 'https://www.numbeo.com/cost-of-living/in/Boston?displayCurrency=USD',
 537: 'https://www.numbeo.com/cost-of-living/in/Anchorage?displayCurrency=USD',
 36: 'https://www.numbeo.com/cost-of-living/in/Copenhagen?displayCurrency=USD',
 12: 'https://www.numbeo.com/cost-of-living/in/Oakland?displayCurrency=USD',
 37: 'https://www.numbeo.com/cost-of-living/in/Miami?displayCurrency=USD',
 129: 'https://www.numbeo.com/cost-of-living/in/Haifa?displayCurrency=USD',
 27: 'https://www.numbeo.com/cost-of-living/in/Los-Angeles?displayCurrency=USD',
 20: 'https://www.numbeo.com/cost-of-living/in/San-Diego?displayCurrency=USD',
 143: 'https://www.numbeo.com/cost-of-living/in/Amsterdam?displayCurrency=USD',
 126: 'https://www.numbeo.com/cost-of-living/in/Stockholm?displayCurrency=USD',
 54: 'https://www.numbeo.com/cost-of-living/in/Sydney?displayCurrency=USD',
 538: 'https://www.numbeo.com/cost-of-living/in/Arlington?displayCurrency=USD',
 539: 'https://www.numbeo.com/cost-of-living/in/Aarhus-Denmark?displayCurrency=USD',
 540: 'https://www.numbeo.com/cost-of-living/in/Irvine?displayCurrency=USD',
 150: 'https://www.numbeo.com/cost-of-living/in/Petah-Tikva?displayCurrency=USD',
 55: 'https://www.numbeo.com/cost-of-living/in/Aalborg?displayCurrency=USD',
 109: 'https://www.numbeo.com/cost-of-living/in/Luxembourg?displayCurrency=USD',
 53: 'https://www.numbeo.com/cost-of-living/in/Philadelphia?displayCurrency=USD',
 73: 'https://www.numbeo.com/cost-of-living/in/Fort-Lauderdale?displayCurrency=USD',
 32: 'https://www.numbeo.com/cost-of-living/in/Sacramento?displayCurrency=USD',
 541: 'https://www.numbeo.com/cost-of-living/in/Haarlem?displayCurrency=USD',
 121: 'https://www.numbeo.com/cost-of-living/in/Beersheba?displayCurrency=USD',
 63: 'https://www.numbeo.com/cost-of-living/in/Paris?displayCurrency=USD',
 51: 'https://www.numbeo.com/cost-of-living/in/New-Orleans?displayCurrency=USD',
 542: 'https://www.numbeo.com/cost-of-living/in/Jersey-City?displayCurrency=USD',
 137: 'https://www.numbeo.com/cost-of-living/in/Guildford?displayCurrency=USD',
 31: 'https://www.numbeo.com/cost-of-living/in/Portland?displayCurrency=USD',
 21: 'https://www.numbeo.com/cost-of-living/in/Canberra?displayCurrency=USD',
 159: 'https://www.numbeo.com/cost-of-living/in/Utrecht?displayCurrency=USD',
 56: 'https://www.numbeo.com/cost-of-living/in/Melbourne?displayCurrency=USD',
 69: 'https://www.numbeo.com/cost-of-living/in/Salzburg?displayCurrency=USD',
 39: 'https://www.numbeo.com/cost-of-living/in/Chicago?displayCurrency=USD',
 89: 'https://www.numbeo.com/cost-of-living/in/Munich?displayCurrency=USD',
 64: 'https://www.numbeo.com/cost-of-living/in/Reno?displayCurrency=USD',
 125: 'https://www.numbeo.com/cost-of-living/in/Oxford?displayCurrency=USD',
 543: 'https://www.numbeo.com/cost-of-living/in/Albany?displayCurrency=USD',
 80: 'https://www.numbeo.com/cost-of-living/in/Nice?displayCurrency=USD',
 65: 'https://www.numbeo.com/cost-of-living/in/Dublin?displayCurrency=USD',
 45: 'https://www.numbeo.com/cost-of-living/in/Espoo?displayCurrency=USD',
 90: 'https://www.numbeo.com/cost-of-living/in/Milan?displayCurrency=USD',
 48: 'https://www.numbeo.com/cost-of-living/in/Atlanta?displayCurrency=USD',
 183: 'https://www.numbeo.com/cost-of-living/in/Vienna?displayCurrency=USD',
 231: 'https://www.numbeo.com/cost-of-living/in/Rotterdam?displayCurrency=USD',
 68: 'https://www.numbeo.com/cost-of-living/in/Dallas?displayCurrency=USD',
 35: 'https://www.numbeo.com/cost-of-living/in/Odense?displayCurrency=USD',
 140: 'https://www.numbeo.com/cost-of-living/in/Brighton?displayCurrency=USD',
 196: 'https://www.numbeo.com/cost-of-living/in/Delft?displayCurrency=USD',
 40: 'https://www.numbeo.com/cost-of-living/in/Denver?displayCurrency=USD',
 544: 'https://www.numbeo.com/cost-of-living/in/Colorado-Springs?displayCurrency=USD',
 104: 'https://www.numbeo.com/cost-of-living/in/Cambridge?displayCurrency=USD',
 77: 'https://www.numbeo.com/cost-of-living/in/Phoenix?displayCurrency=USD',
 95: 'https://www.numbeo.com/cost-of-living/in/Frankfurt?displayCurrency=USD',
 245: 'https://www.numbeo.com/cost-of-living/in/The-Hague-Den-Haag-Netherlands?displayCurrency=USD',
 60: 'https://www.numbeo.com/cost-of-living/in/Minneapolis?displayCurrency=USD',
 111: 'https://www.numbeo.com/cost-of-living/in/Helsinki?displayCurrency=USD',
 93: 'https://www.numbeo.com/cost-of-living/in/Hong-Kong?displayCurrency=USD',
 38: 'https://www.numbeo.com/cost-of-living/in/Buffalo?displayCurrency=USD',
 194: 'https://www.numbeo.com/cost-of-living/in/Gold-Coast?displayCurrency=USD',
 179: 'https://www.numbeo.com/cost-of-living/in/Marseille?displayCurrency=USD',
 545: 'https://www.numbeo.com/cost-of-living/in/Baltimore?displayCurrency=USD',
 108: 'https://www.numbeo.com/cost-of-living/in/Saint-Louis?displayCurrency=USD',
 153: 'https://www.numbeo.com/cost-of-living/in/Wiesbaden?displayCurrency=USD',
 79: 'https://www.numbeo.com/cost-of-living/in/Lyon?displayCurrency=USD',
 182: 'https://www.numbeo.com/cost-of-living/in/Galway?displayCurrency=USD',
 157: 'https://www.numbeo.com/cost-of-living/in/Karlsruhe?displayCurrency=USD',
 88: 'https://www.numbeo.com/cost-of-living/in/Dusseldorf?displayCurrency=USD',
 25: 'https://www.numbeo.com/cost-of-living/in/Adelaide?displayCurrency=USD',
 546: 'https://www.numbeo.com/cost-of-living/in/Strasbourg?displayCurrency=USD',
 49: 'https://www.numbeo.com/cost-of-living/in/Perth?displayCurrency=USD',
 59: 'https://www.numbeo.com/cost-of-living/in/Greenville?displayCurrency=USD',
 185: 'https://www.numbeo.com/cost-of-living/in/Edinburgh?displayCurrency=USD',
 547: 'https://www.numbeo.com/cost-of-living/in/Erfurt-Germany?displayCurrency=USD',
 160: 'https://www.numbeo.com/cost-of-living/in/Essen?displayCurrency=USD',
 162: 'https://www.numbeo.com/cost-of-living/in/Gent?displayCurrency=USD',
 47: 'https://www.numbeo.com/cost-of-living/in/Darmstadt?displayCurrency=USD',
 141: 'https://www.numbeo.com/cost-of-living/in/Graz?displayCurrency=USD',
 144: 'https://www.numbeo.com/cost-of-living/in/Heidelberg?displayCurrency=USD',
 113: 'https://www.numbeo.com/cost-of-living/in/Cologne?displayCurrency=USD',
 548: 'https://www.numbeo.com/cost-of-living/in/Oklahoma-City?displayCurrency=USD',
 127: 'https://www.numbeo.com/cost-of-living/in/Antwerp?displayCurrency=USD',
 170: 'https://www.numbeo.com/cost-of-living/in/Reading?displayCurrency=USD',
 229: 'https://www.numbeo.com/cost-of-living/in/Southampton?displayCurrency=USD',
 57: 'https://www.numbeo.com/cost-of-living/in/Fort-Worth?displayCurrency=USD',
 101: 'https://www.numbeo.com/cost-of-living/in/Spokane?displayCurrency=USD',
 85: 'https://www.numbeo.com/cost-of-living/in/Orlando?displayCurrency=USD',
 549: 'https://www.numbeo.com/cost-of-living/in/Mainz?displayCurrency=USD',
 550: 'https://www.numbeo.com/cost-of-living/in/Regensburg?displayCurrency=USD',
 86: 'https://www.numbeo.com/cost-of-living/in/Leiden?displayCurrency=USD',
 128: 'https://www.numbeo.com/cost-of-living/in/Cork?displayCurrency=USD',
 50: 'https://www.numbeo.com/cost-of-living/in/Nashville?displayCurrency=USD',
 96: 'https://www.numbeo.com/cost-of-living/in/Las-Vegas?displayCurrency=USD',
 119: 'https://www.numbeo.com/cost-of-living/in/Hamburg?displayCurrency=USD',
 173: 'https://www.numbeo.com/cost-of-living/in/Bristol?displayCurrency=USD',
 158: 'https://www.numbeo.com/cost-of-living/in/Richmond?displayCurrency=USD',
 168: 'https://www.numbeo.com/cost-of-living/in/Eindhoven?displayCurrency=USD',
 193: 'https://www.numbeo.com/cost-of-living/in/Augsburg?displayCurrency=USD',
 551: 'https://www.numbeo.com/cost-of-living/in/Pisa?displayCurrency=USD',
 171: 'https://www.numbeo.com/cost-of-living/in/Stuttgart?displayCurrency=USD',
 78: 'https://www.numbeo.com/cost-of-living/in/San-Juan?displayCurrency=USD',
 106: 'https://www.numbeo.com/cost-of-living/in/Brussels?displayCurrency=USD',
 34: 'https://www.numbeo.com/cost-of-living/in/Tampa?displayCurrency=USD',
 246: 'https://www.numbeo.com/cost-of-living/in/Malmo?displayCurrency=USD',
 253: 'https://www.numbeo.com/cost-of-living/in/Aberdeen?displayCurrency=USD',
 230: 'https://www.numbeo.com/cost-of-living/in/Uppsala?displayCurrency=USD',
 97: 'https://www.numbeo.com/cost-of-living/in/Columbus?displayCurrency=USD',
 46: 'https://www.numbeo.com/cost-of-living/in/Brisbane?displayCurrency=USD',
 552: 'https://www.numbeo.com/cost-of-living/in/Kiel?displayCurrency=USD',
 122: 'https://www.numbeo.com/cost-of-living/in/Berlin?displayCurrency=USD',
 136: 'https://www.numbeo.com/cost-of-living/in/Bordeaux?displayCurrency=USD',
 192: 'https://www.numbeo.com/cost-of-living/in/Groningen?displayCurrency=USD',
 134: 'https://www.numbeo.com/cost-of-living/in/Toulouse?displayCurrency=USD',
 155: 'https://www.numbeo.com/cost-of-living/in/Nuremberg?displayCurrency=USD',
 43: 'https://www.numbeo.com/cost-of-living/in/Charlotte?displayCurrency=USD',
 553: 'https://www.numbeo.com/cost-of-living/in/Ann-Arbor?displayCurrency=USD',
 120: 'https://www.numbeo.com/cost-of-living/in/Indianapolis?displayCurrency=USD',
 102: 'https://www.numbeo.com/cost-of-living/in/Freiburg-Im-Breisgau?displayCurrency=USD',
 66: 'https://www.numbeo.com/cost-of-living/in/Victoria?displayCurrency=USD',
 254: 'https://www.numbeo.com/cost-of-living/in/Birmingham?displayCurrency=USD',
 83: 'https://www.numbeo.com/cost-of-living/in/Vancouver?displayCurrency=USD',
 131: 'https://www.numbeo.com/cost-of-living/in/Bonn?displayCurrency=USD',
 98: 'https://www.numbeo.com/cost-of-living/in/Madison?displayCurrency=USD',
 116: 'https://www.numbeo.com/cost-of-living/in/Linz?displayCurrency=USD',
 554: 'https://www.numbeo.com/cost-of-living/in/York?displayCurrency=USD',
 151: 'https://www.numbeo.com/cost-of-living/in/Turku?displayCurrency=USD',
 233: 'https://www.numbeo.com/cost-of-living/in/Dresden?displayCurrency=USD',
 154: 'https://www.numbeo.com/cost-of-living/in/Florence?displayCurrency=USD',
 177: 'https://www.numbeo.com/cost-of-living/in/Bremen?displayCurrency=USD',
 209: 'https://www.numbeo.com/cost-of-living/in/Brescia?displayCurrency=USD',
 204: 'https://www.numbeo.com/cost-of-living/in/Limerick?displayCurrency=USD',
 555: 'https://www.numbeo.com/cost-of-living/in/Birmingham-AL?displayCurrency=USD',
 61: 'https://www.numbeo.com/cost-of-living/in/Pittsburgh?displayCurrency=USD',
 176: 'https://www.numbeo.com/cost-of-living/in/Manchester?displayCurrency=USD',
 178: 'https://www.numbeo.com/cost-of-living/in/Bologna?displayCurrency=USD',
 67: 'https://www.numbeo.com/cost-of-living/in/Seoul?displayCurrency=USD',
 94: 'https://www.numbeo.com/cost-of-living/in/Toronto?displayCurrency=USD',
 145: 'https://www.numbeo.com/cost-of-living/in/Hanover?displayCurrency=USD',
 62: 'https://www.numbeo.com/cost-of-living/in/Austin?displayCurrency=USD',
 195: 'https://www.numbeo.com/cost-of-living/in/Surrey?displayCurrency=USD',
 227: 'https://www.numbeo.com/cost-of-living/in/Belfast?displayCurrency=USD',
 237: 'https://www.numbeo.com/cost-of-living/in/Milton-Keynes?displayCurrency=USD',
 225: 'https://www.numbeo.com/cost-of-living/in/Gothenburg?displayCurrency=USD',
 133: 'https://www.numbeo.com/cost-of-living/in/Boise?displayCurrency=USD',
 165: 'https://www.numbeo.com/cost-of-living/in/Glasgow?displayCurrency=USD',
 556: 'https://www.numbeo.com/cost-of-living/in/Gainesville?displayCurrency=USD',
 215: 'https://www.numbeo.com/cost-of-living/in/Bournemouth?displayCurrency=USD',
 236: 'https://www.numbeo.com/cost-of-living/in/Newcastle-Upon-Tyne?displayCurrency=USD',
 172: 'https://www.numbeo.com/cost-of-living/in/Mannheim?displayCurrency=USD',
 557: 'https://www.numbeo.com/cost-of-living/in/Vancouver-WA?displayCurrency=USD',
 105: 'https://www.numbeo.com/cost-of-living/in/Milwaukee?displayCurrency=USD',
 191: 'https://www.numbeo.com/cost-of-living/in/Leeds?displayCurrency=USD',
 223: 'https://www.numbeo.com/cost-of-living/in/Leipzig?displayCurrency=USD',
 124: 'https://www.numbeo.com/cost-of-living/in/Kansas-City?displayCurrency=USD',
 259: 'https://www.numbeo.com/cost-of-living/in/Verona?displayCurrency=USD',
 558: 'https://www.numbeo.com/cost-of-living/in/Lethbridge?displayCurrency=USD',
 41: 'https://www.numbeo.com/cost-of-living/in/Raleigh?displayCurrency=USD',
 248: 'https://www.numbeo.com/cost-of-living/in/Cardiff?displayCurrency=USD',
 239: 'https://www.numbeo.com/cost-of-living/in/Treviso?displayCurrency=USD',
 222: 'https://www.numbeo.com/cost-of-living/in/Aachen?displayCurrency=USD',
 201: 'https://www.numbeo.com/cost-of-living/in/Liverpool?displayCurrency=USD',
 220: 'https://www.numbeo.com/cost-of-living/in/Dundee?displayCurrency=USD',
 202: 'https://www.numbeo.com/cost-of-living/in/Kitchener?displayCurrency=USD',
 130: 'https://www.numbeo.com/cost-of-living/in/Salt-Lake-City?displayCurrency=USD',
 142: 'https://www.numbeo.com/cost-of-living/in/Grenoble?displayCurrency=USD',
 58: 'https://www.numbeo.com/cost-of-living/in/Omaha?displayCurrency=USD',
 187: 'https://www.numbeo.com/cost-of-living/in/Nottingham?displayCurrency=USD',
 559: 'https://www.numbeo.com/cost-of-living/in/Erlangen?displayCurrency=USD',
 560: 'https://www.numbeo.com/cost-of-living/in/Wichita?displayCurrency=USD',
 205: 'https://www.numbeo.com/cost-of-living/in/Lund?displayCurrency=USD',
 138: 'https://www.numbeo.com/cost-of-living/in/Montpellier?displayCurrency=USD',
 561: 'https://www.numbeo.com/cost-of-living/in/Kassel-Germany?displayCurrency=USD',
 562: 'https://www.numbeo.com/cost-of-living/in/Chemnitz?displayCurrency=USD',
 563: 'https://www.numbeo.com/cost-of-living/in/Rochester?displayCurrency=USD',
 198: 'https://www.numbeo.com/cost-of-living/in/Lille?displayCurrency=USD',
 110: 'https://www.numbeo.com/cost-of-living/in/Jacksonville?displayCurrency=USD',
 112: 'https://www.numbeo.com/cost-of-living/in/St-John%27s-Newfoundland-and-Labrador-Canada?displayCurrency=USD',
 214: 'https://www.numbeo.com/cost-of-living/in/Knoxville?displayCurrency=USD',
 87: 'https://www.numbeo.com/cost-of-living/in/Houston?displayCurrency=USD',
 75: 'https://www.numbeo.com/cost-of-living/in/Auckland?displayCurrency=USD',
 82: 'https://www.numbeo.com/cost-of-living/in/Wellington?displayCurrency=USD',
 219: 'https://www.numbeo.com/cost-of-living/in/Sliema?displayCurrency=USD',
 564: 'https://www.numbeo.com/cost-of-living/in/Braunschweig?displayCurrency=USD',
 565: 'https://www.numbeo.com/cost-of-living/in/Bolzano-Bozen?displayCurrency=USD',
 266: 'https://www.numbeo.com/cost-of-living/in/Coventry?displayCurrency=USD',
 147: 'https://www.numbeo.com/cost-of-living/in/San-Antonio?displayCurrency=USD',
 91: 'https://www.numbeo.com/cost-of-living/in/Calgary?displayCurrency=USD',
 566: 'https://www.numbeo.com/cost-of-living/in/Tulsa?displayCurrency=USD',
 71: 'https://www.numbeo.com/cost-of-living/in/Cleveland?displayCurrency=USD',
 180: 'https://www.numbeo.com/cost-of-living/in/Leuven?displayCurrency=USD',
 567: 'https://www.numbeo.com/cost-of-living/in/Trento?displayCurrency=USD',
 44: 'https://www.numbeo.com/cost-of-living/in/Tucson?displayCurrency=USD',
 265: 'https://www.numbeo.com/cost-of-living/in/Tallinn?displayCurrency=USD',
 238: 'https://www.numbeo.com/cost-of-living/in/Padova?displayCurrency=USD',
 199: 'https://www.numbeo.com/cost-of-living/in/Kelowna?displayCurrency=USD',
 224: 'https://www.numbeo.com/cost-of-living/in/Sheffield?displayCurrency=USD',
 52: 'https://www.numbeo.com/cost-of-living/in/Villach-Austria?displayCurrency=USD',
 188: 'https://www.numbeo.com/cost-of-living/in/Saskatoon?displayCurrency=USD',
 118: 'https://www.numbeo.com/cost-of-living/in/Edmonton?displayCurrency=USD',
 117: 'https://www.numbeo.com/cost-of-living/in/Halifax?displayCurrency=USD',
 114: 'https://www.numbeo.com/cost-of-living/in/Nanaimo?displayCurrency=USD',
 226: 'https://www.numbeo.com/cost-of-living/in/Mississauga?displayCurrency=USD',
 92: 'https://www.numbeo.com/cost-of-living/in/Ottawa?displayCurrency=USD',
 232: 'https://www.numbeo.com/cost-of-living/in/Cagliari?displayCurrency=USD',
 72: 'https://www.numbeo.com/cost-of-living/in/Albuquerque?displayCurrency=USD',
 235: 'https://www.numbeo.com/cost-of-living/in/Cincinnati?displayCurrency=USD',
 244: 'https://www.numbeo.com/cost-of-living/in/Regina?displayCurrency=USD',
 240: 'https://www.numbeo.com/cost-of-living/in/Limassol?displayCurrency=USD',
 166: 'https://www.numbeo.com/cost-of-living/in/London-Canada?displayCurrency=USD',
 207: 'https://www.numbeo.com/cost-of-living/in/Guelph?displayCurrency=USD',
 197: 'https://www.numbeo.com/cost-of-living/in/Genoa?displayCurrency=USD',
 123: 'https://www.numbeo.com/cost-of-living/in/Valletta?displayCurrency=USD',
 148: 'https://www.numbeo.com/cost-of-living/in/Louisville?displayCurrency=USD',
 568: 'https://www.numbeo.com/cost-of-living/in/Columbia?displayCurrency=USD',
 208: 'https://www.numbeo.com/cost-of-living/in/Dubai?displayCurrency=USD',
 175: 'https://www.numbeo.com/cost-of-living/in/Trieste?displayCurrency=USD',
 167: 'https://www.numbeo.com/cost-of-living/in/Christchurch?displayCurrency=USD',
 184: 'https://www.numbeo.com/cost-of-living/in/Montreal?displayCurrency=USD',
 247: 'https://www.numbeo.com/cost-of-living/in/Brampton?displayCurrency=USD',
 203: 'https://www.numbeo.com/cost-of-living/in/Rome?displayCurrency=USD',
 163: 'https://www.numbeo.com/cost-of-living/in/Winnipeg?displayCurrency=USD',
 135: 'https://www.numbeo.com/cost-of-living/in/Quebec-City?displayCurrency=USD',
 242: 'https://www.numbeo.com/cost-of-living/in/Turin?displayCurrency=USD',
 161: 'https://www.numbeo.com/cost-of-living/in/Hamilton?displayCurrency=USD',
 569: 'https://www.numbeo.com/cost-of-living/in/Huntsville?displayCurrency=USD',
 275: 'https://www.numbeo.com/cost-of-living/in/Naples?displayCurrency=USD',
 570: 'https://www.numbeo.com/cost-of-living/in/Moncton?displayCurrency=USD',
 255: 'https://www.numbeo.com/cost-of-living/in/Rimini?displayCurrency=USD',
 298: 'https://www.numbeo.com/cost-of-living/in/Madrid?displayCurrency=USD',
 269: 'https://www.numbeo.com/cost-of-living/in/Barcelona?displayCurrency=USD',
 571: 'https://www.numbeo.com/cost-of-living/in/Remagen-Germany?displayCurrency=USD',

In [8]:
df_missing_climate = pd.read_pickle("./data/missing_climate_links.pkl")
len(df_missing_climate)

45

In [25]:
df_missing_climate.head()

,city_id,geonameid,numbeo_link,auto_climate_link,climate_link,climate_link_source,climate_status
2,491,3435910.0,https://www.numbeo.com/cost-of-living/in/Bueno...,https://www.weather-atlas.com/en/Argentina/Bue...,None,failed,failed
3,576,3860259.0,https://www.numbeo.com/cost-of-living/in/Cordo...,https://www.weather-atlas.com/en/Argentina/Cor...,None,failed,failed
102,329,3069011.0,https://www.numbeo.com/cost-of-living/in/Olomo...,https://www.weather-atlas.com/en/Czech-Republi...,None,failed,failed
133,564,2945024.0,https://www.numbeo.com/cost-of-living/in/Braun...,https://www.weather-atlas.com/en/Germany/Braun...,None,failed,failed
138,561,2892518.0,https://www.numbeo.com/cost-of-living/in/Kasse...,https://www.weather-atlas.com/en/Germany/Kasse...,None,failed,failed

In [9]:
df_climate = pd.read_pickle("./data/climate_links.pkl")
len(df_climate)

527

In [27]:
df_climate.sort_values(by="city_id").head(12)

,city_id,geonameid,numbeo_link,auto_climate_link,climate_link,climate_link_source,climate_status
388,2,2661604.0,https://www.numbeo.com/cost-of-living/in/Basel...,https://www.weather-atlas.com/en/Switzerland/B...,https://www.weather-atlas.com/en/Switzerland/B...,auto,ok
386,3,2657896.0,https://www.numbeo.com/cost-of-living/in/Zuric...,https://www.weather-atlas.com/en/Switzerland/Z...,https://www.weather-atlas.com/en/Switzerland/Z...,auto,ok
385,5,2659994.0,https://www.numbeo.com/cost-of-living/in/Lausa...,https://www.weather-atlas.com/en/Switzerland/L...,https://www.weather-atlas.com/en/Switzerland/L...,auto,ok
72,7,3580661.0,https://www.numbeo.com/cost-of-living/in/Georg...,https://www.weather-atlas.com/en/Cayman-Island...,https://www.weather-atlas.com/en/Cayman-Island...,auto,ok
389,8,2660646.0,https://www.numbeo.com/cost-of-living/in/Genev...,https://www.weather-atlas.com/en/Switzerland/G...,https://www.weather-atlas.com/en/Switzerland/G...,auto,ok
390,9,2661552.0,https://www.numbeo.com/cost-of-living/in/Bern?...,https://www.weather-atlas.com/en/Switzerland/B...,https://www.weather-atlas.com/en/Switzerland/B...,auto,ok
451,11,5128581.0,https://www.numbeo.com/cost-of-living/in/New-Y...,https://www.weather-atlas.com/en/New-York-usa/...,https://www.weather-atlas.com/en/New-York-usa/...,auto,ok
470,12,5378538.0,https://www.numbeo.com/cost-of-living/in/Oakla...,https://www.weather-atlas.com/en/California-us...,https://www.weather-atlas.com/en/California-us...,auto,ok
453,13,5856195.0,https://www.numbeo.com/cost-of-living/in/Honol...,https://www.weather-atlas.com/en/Hawaii-usa/Ho...,https://www.weather-atlas.com/en/Hawaii-usa/Ho...,auto,ok
450,14,5391959.0,https://www.numbeo.com/cost-of-living/in/San-F...,https://www.weather-atlas.com/en/California-us...,https://www.weather-atlas.com/en/California-us...,auto,ok
477,15,5809844.0,https://www.numbeo.com/cost-of-living/in/Seatt...,https://www.weather-atlas.com/en/Washington-us...,https://www.weather-atlas.com/en/Washington-us...,auto,ok
173,16,3413829.0,https://www.numbeo.com/cost-of-living/in/Reykj...,https://www.weather-atlas.com/en/Iceland/Reykj...,https://www.weather-atlas.com/en/Iceland/Reykj...,auto,ok

In [16]:
df_missing_climate.loc[:, ["city_id", "auto_climate_link"]].to_dict(orient="records")

[{'city_id': 491,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Argentina/Buenos-Aires-climate'},
 {'city_id': 576,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Argentina/Cordoba-climate'},
 {'city_id': 329,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Czech-Republic/Olomouc-climate'},
 {'city_id': 564,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Germany/Braunschweig-climate'},
 {'city_id': 561,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Germany/Kassel-climate'},
 {'city_id': 623,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Rajkot-climate'},
 {'city_id': 622,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Lucknow-climate'},
 {'city_id': 621,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Guwahati-climate'},
 {'city_id': 620,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Indore-climate'},
 {'city_id': 619,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Jaipur-climate'},
 {'city_id': 618,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Surat-climate'},
 {'city_id': 617,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Bhopal-climate'},
 {'city_id': 616,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Kochi-climate'},
 {'city_id': 615,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Bhubaneswar-climate'},
 {'city_id': 614,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Patna-climate'},
 {'city_id': 613,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Kolkata-climate'},
 {'city_id': 612,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Chennai-climate'},
 {'city_id': 610,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Chandigarh-climate'},
 {'city_id': 609,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Thane-climate'},
 {'city_id': 608,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Navi-Mumbai-climate'},
 {'city_id': 606,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Ahmedabad-climate'},
 {'city_id': 605,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Hyderabad-climate'},
 {'city_id': 603,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Bangalore-climate'},
 {'city_id': 602,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Pune-climate'},
 {'city_id': 524,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Delhi-climate'},
 {'city_id': 600,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Gurgaon-climate'},
 {'city_id': 518,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Mumbai-climate'},
 {'city_id': 611,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Vadodara-climate'},
 {'city_id': 604,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Noida-climate'},
 {'city_id': 624,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Coimbatore-climate'},
 {'city_id': 586,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Indonesia/Bali-climate'},
 {'city_id': 565,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Italy/Bolzano-Bozen-climate'},
 {'city_id': 572,
  'auto_climate_link': "https://www.weather-atlas.com/en/Italy/Reggio-Nell'emilia-climate"},
 {'city_id': 567,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Italy/Trento-climate'},
 {'city_id': 580,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Mexico/Aguascalientes-climate'},
 {'city_id': 506,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Nepal/Kathmandu-climate'},
 {'city_id': 587,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Russia/Chelyabinsk-climate'},
 {'city_id': 495,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Lviv-climate'},
 {'city_id': 472,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Dnipro-climate'},
 {'city_id': 479,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Kharkiv-climate'},
 {'city_id': 461,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Kiev-climate'},
 {'city_id': 475,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Odessa-climate'},
 {'city_id': 471,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Vietnam/Da-Nang-climate'},
 {'city_id': 450,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Vietnam/Hanoi-climate'},
 {'city_id': 435,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Vietnam/Ho-Chi-Minh-City-climate'}]

In [21]:
# Сортируем и сразу выводим нужные колонки
df_missing_climate.sort_values(by="city_id").loc[
    :, ["city_id", "auto_climate_link"]
].to_dict(orient="records")

[{'city_id': 329,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Czech-Republic/Olomouc-climate'},
 {'city_id': 435,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Vietnam/Ho-Chi-Minh-City-climate'},
 {'city_id': 450,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Vietnam/Hanoi-climate'},
 {'city_id': 461,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Kiev-climate'},
 {'city_id': 471,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Vietnam/Da-Nang-climate'},
 {'city_id': 472,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Dnipro-climate'},
 {'city_id': 475,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Odessa-climate'},
 {'city_id': 479,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Kharkiv-climate'},
 {'city_id': 491,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Argentina/Buenos-Aires-climate'},
 {'city_id': 495,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Ukraine/Lviv-climate'},
 {'city_id': 506,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Nepal/Kathmandu-climate'},
 {'city_id': 518,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Mumbai-climate'},
 {'city_id': 524,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Delhi-climate'},
 {'city_id': 561,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Germany/Kassel-climate'},
 {'city_id': 564,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Germany/Braunschweig-climate'},
 {'city_id': 565,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Italy/Bolzano-Bozen-climate'},
 {'city_id': 567,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Italy/Trento-climate'},
 {'city_id': 572,
  'auto_climate_link': "https://www.weather-atlas.com/en/Italy/Reggio-Nell'emilia-climate"},
 {'city_id': 576,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Argentina/Cordoba-climate'},
 {'city_id': 580,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Mexico/Aguascalientes-climate'},
 {'city_id': 586,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Indonesia/Bali-climate'},
 {'city_id': 587,
  'auto_climate_link': 'https://www.weather-atlas.com/en/Russia/Chelyabinsk-climate'},
 {'city_id': 600,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Gurgaon-climate'},
 {'city_id': 602,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Pune-climate'},
 {'city_id': 603,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Bangalore-climate'},
 {'city_id': 604,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Noida-climate'},
 {'city_id': 605,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Hyderabad-climate'},
 {'city_id': 606,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Ahmedabad-climate'},
 {'city_id': 608,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Navi-Mumbai-climate'},
 {'city_id': 609,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Thane-climate'},
 {'city_id': 610,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Chandigarh-climate'},
 {'city_id': 611,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Vadodara-climate'},
 {'city_id': 612,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Chennai-climate'},
 {'city_id': 613,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Kolkata-climate'},
 {'city_id': 614,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Patna-climate'},
 {'city_id': 615,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Bhubaneswar-climate'},
 {'city_id': 616,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Kochi-climate'},
 {'city_id': 617,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Bhopal-climate'},
 {'city_id': 618,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Surat-climate'},
 {'city_id': 619,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Jaipur-climate'},
 {'city_id': 620,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Indore-climate'},
 {'city_id': 621,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Guwahati-climate'},
 {'city_id': 622,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Lucknow-climate'},
 {'city_id': 623,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Rajkot-climate'},
 {'city_id': 624,
  'auto_climate_link': 'https://www.weather-atlas.com/en/India/Coimbatore-climate'}]

# Scraping Numbeo

In [2]:
NUMBEO_SAMPLE_URL = (
    "https://www.numbeo.com/cost-of-living/in/New-York?displayCurrency=USD"
)

In [3]:
table = pd.read_html(NUMBEO_SAMPLE_URL)

In [5]:
table[0]

    0                                                  1   2
0 NaN  whenDocReady(function() {  jQuery('#city_selec... NaN

In [6]:
table[1]

,Restaurants,Edit,Range
0,Meal at an Inexpensive Restaurant,25.00 $,15.00-50.00
1,Meal for Two at a Mid-Range Restaurant (Three ...,140.00 $,80.00-228.00
2,Combo Meal at McDonald's (or Equivalent Fast-F...,14.00 $,12.00-16.00
3,Domestic Draft Beer (0.5 Liter),8.00 $,5.00-12.00
4,Imported Beer (0.33 Liter Bottle),10.00 $,8.00-12.00
...,...,...,...
68,Price per Square Meter to Buy Apartment Outsid...,"9,472.39 $","6,103.14-18,298.65"
69,NaN,NaN,NaN
70,Salaries And Financing,Edit,NaN
71,Average Monthly Net Salary (After Tax),"5,266.86 $",NaN
72,"Annual Mortgage Interest Rate (20-Year Fixed, ...",6.76,6.00-7.60